// Re-export from generated types (auto-generated by ts-rs)
export type {
  Archive,
  DiffResult,
  DiffHunk,
  DiffChange,
  DiffStats,
  Statistics,
} from './generated';

// 增强差异对比类型
export type {
  DiffSummary,
  ChangeSummary,
  ChangeLocation,
  ChangeDistribution,
  AffectedRegion,
  EnhancedDiffResult,
  FileType,
  ContentPreview,
} from './diff';
